//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 2/16/2016 5:10:22 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Linq;
using System.Runtime.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace dotConnectSalesforce.Edml.Entities
{
    public partial class SalesforceEdmlContext : DbContext
    {
        #region Constructors

        /// <summary>
        /// Initialize a new SalesforceEdmlContext object.
        /// </summary>
        public SalesforceEdmlContext() :
                base(@"name=SalesforceEdmlContext")
        {
            Configure();
        }

        /// <summary>
        /// Initializes a new SalesforceEdmlContext object using the connection string found in the 'SalesforceEdmlContext' section of the application configuration file.
        /// </summary>
        public SalesforceEdmlContext(string nameOrConnectionString) :
                base(nameOrConnectionString)
        {
            Configure();
        }

        /// <summary>
        /// Initialize a new SalesforceEdmlContext object.
        /// </summary>
        public SalesforceEdmlContext(DbConnection existingConnection, bool contextOwnsConnection) :
                base(existingConnection, contextOwnsConnection)
        {
            Configure();
        }

        /// <summary>
        /// Initialize a new SalesforceEdmlContext object.
        /// </summary>
        public SalesforceEdmlContext(ObjectContext objectContext, bool dbContextOwnsObjectContext) :
                base(objectContext, dbContextOwnsObjectContext)
        {
            Configure();
        }

        /// <summary>
        /// Initialize a new SalesforceEdmlContext object.
        /// </summary>
        public SalesforceEdmlContext(string nameOrConnectionString, DbCompiledModel model) :
                base(nameOrConnectionString, model)
        {
            Configure();
        }

        /// <summary>
        /// Initialize a new SalesforceEdmlContext object.
        /// </summary>
        public SalesforceEdmlContext(DbConnection existingConnection, DbCompiledModel model, bool contextOwnsConnection) :
                base(existingConnection, model, contextOwnsConnection)
        {
            Configure();
        }

        private void Configure()
        {
            this.Configuration.AutoDetectChangesEnabled = true;
            this.Configuration.LazyLoadingEnabled = true;
            this.Configuration.ProxyCreationEnabled = true;
            this.Configuration.ValidateOnSaveEnabled = true;
        }

        #endregion

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Configurations.Add(new Mapping.AddressConfiguration());

            #region Disabled conventions


            #endregion

        }

    
        /// <summary>
        /// There are no comments for Address in the schema.
        /// </summary>
        public virtual DbSet<Address> Addresses { get; set; }
    }
}
