//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 2/16/2016 5:10:22 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.Data.Entity.ModelConfiguration;

namespace dotConnectSalesforce.Edml.Entities.Mapping
{

    public partial class AddressConfiguration : EntityTypeConfiguration<Address>
    {

        public AddressConfiguration()
        {
            this
                .HasKey(p => p.Id)
                .ToTable("Address");
            // Properties:
            this
                .Property(p => p.Id)
                    .IsRequired()
                    .HasMaxLength(18)
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Computed)
                    .HasColumnType("string");
            this
                .Property(p => p.OwnerId)
                    .IsRequired()
                    .HasMaxLength(18)
                    .HasColumnType("string");
            this
                .Property(p => p.IsDeleted)
                    .IsRequired()
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Computed)
                    .HasColumnType("boolean");
            this
                .Property(p => p.Name)
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Computed)
                    .HasColumnType("string");
            this
                .Property(p => p.LastViewedDate)
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Computed)
                    .HasColumnType("datetime");
            this
                .Property(p => p.LastReferencedDate)
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Computed)
                    .HasColumnType("datetime");
            this
                .Property(p => p.NameOfHotelMotelComplex)
                    .HasColumnName(@"Name_of_Hotel_Motel_Complex")
                    .HasMaxLength(255)
                    .HasColumnType("string");
            this
                .Property(p => p.Street)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("string");
            this
                .Property(p => p.StreetAddress2)
                    .HasColumnName(@"Street_Address_2")
                    .HasMaxLength(100)
                    .HasColumnType("string");
            this
                .Property(p => p.City)
                    .IsRequired()
                    .HasMaxLength(40)
                    .HasColumnType("string");
            this
                .Property(p => p.State)
                    .HasMaxLength(255)
                    .HasColumnType("string");
            this
                .Property(p => p.PostalZipCode)
                    .HasColumnName(@"Postal_Zip_Code")
                    .HasMaxLength(10)
                    .HasColumnType("string");
            this
                .Property(p => p.Profile)
                    .HasMaxLength(18)
                    .HasColumnType("string");
            this
                .Property(p => p.Status)
                    .HasMaxLength(255)
                    .HasColumnType("string");
            this
                .Property(p => p.Type)
                    .HasMaxLength(255)
                    .HasColumnType("string");
            this
                .Property(p => p.UpdateAccount)
                    .HasColumnName(@"Update_Account")
                    .IsRequired()
                    .HasColumnType("boolean");
            this
                .Property(p => p.HousingConcern)
                    .HasColumnName(@"Housing_Concern")
                    .IsRequired()
                    .HasColumnType("boolean");
            this
                .Property(p => p.Account)
                    .HasMaxLength(18)
                    .HasColumnType("string");
            this
                .Property(p => p.LegacyAddressID)
                    .HasColumnName(@"Legacy_Address_ID")
                    .HasMaxLength(15)
                    .HasColumnType("string");
            this
                .Property(p => p.Phone)
                    .HasMaxLength(40)
                    .HasColumnType("string");
            this
                .Property(p => p.Fax)
                    .HasMaxLength(40)
                    .HasColumnType("string");
            this
                .Property(p => p.Email)
                    .HasMaxLength(80)
                    .HasColumnType("string");
            this
                .Property(p => p.Website)
                    .HasMaxLength(255)
                    .HasColumnType("string");
            this
                .Property(p => p.MigratedRecord)
                    .HasColumnName(@"Migrated_Record")
                    .IsRequired()
                    .HasColumnType("boolean");
            this
                .Property(p => p.AtlasHighSchoolID)
                    .HasColumnName(@"Atlas_High_School_ID")
                    .IsRequired()
                    .HasColumnType("boolean");
            this
                .Property(p => p.Contact)
                    .HasMaxLength(18)
                    .HasColumnType("string");
            this
                .Property(p => p.HousingConcernNotes)
                    .HasColumnName(@"Housing_Concern_Notes")
                    .HasMaxLength(32768)
                    .HasColumnType("string");
            this
                .Property(p => p.StateText)
                    .HasColumnName(@"State_Text")
                    .HasMaxLength(40)
                    .HasColumnType("string");
            this
                .Property(p => p.NumberOfBedrooms)
                    .HasColumnName(@"Number_of_bedrooms")
                    .HasColumnType("double");
            this
                .Property(p => p.NumberOfBathrooms)
                    .HasColumnName(@"Number_of_bathrooms")
                    .HasColumnType("double");
            this
                .Property(p => p.IsThereASeparateKitchen)
                    .HasColumnName(@"Is_there_a_separate_kitchen")
                    .HasMaxLength(255)
                    .HasColumnType("string");
            this
                .Property(p => p.NumberOfAssociations)
                    .HasColumnName(@"Number_of_Associations")
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Computed)
                    .HasColumnType("double");
            this
                .Property(p => p.TypeImage)
                    .HasColumnName(@"Type_Image")
                    .HasMaxLength(1300)
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Computed)
                    .HasColumnType("string");
            OnCreated();
        }

        partial void OnCreated();

    }
}
